<?php 
/* Japonca Dil Dosyası */
$dil = array(
	"trdil" 	=> "トルコ語",
	"ingdil" 	=> "英語",
	"almdil"	=> "ドイツ語",
	"jpdil"		=> "日本人",
	"menu1"		=>"ホームページ",
	"menu2"		=>"米国について",
	"menu3"		=>"製品",
	"menu4"		=>"リファレンス",
	"menu5"		=>"今すぐ購入",
	"menu6"		=>"お問い合わせ",
	"slider_baslik" => "SEÇPA ソフトウェア製品",
	"slider_detaylar" => "詳細",
	"iletisim_baslik" => "お問い合わせ。",
	"iletisim_ad" =>"お名前：",
	"iletisim_email" =>"Eメール：",
	"iletisim_mesaj" =>"メッセージ：",
	"iletisim_gonder_button" =>"投稿する",
	"iletisim_ad_desc" => "あなたの姓と名を入力してください。",
	"iletisim_email_desc" => "有効な電子メールアドレスを入力してください。",
	"iletisim_mail_hata" => "E-mailアドレスが有効ではありません。",
	"iletisim_tebrikler" => "おめでとう！!",
	"iletisim_mesaj_gonderildi" => "メッセージは送信されました。できるだけ早く戻ります。",
	"marka_adi" => "Seçpa ソフトウェアおよびインターネット·テクノロジー",
	"buy_liykb" => "あなたのトランザクションが完了するまで、しばらくお待ちください。",
	"satinal" => "買う",
	"lisansi_yenile" => "ライセンスリフレッシュ",
	"ilk_urun_desc" => "Loremイプサムは、単に印刷と植字業界のダミーテキストです。不明なプリンタフォントが1500年代に使用して以来、業界の標準ダミーテキストを混同基づいてギャラリーを作成するときにLoremイプサムは、単に型標本帳の名前です。",
	"ikinci_urun_desc" => "Loremイプサムは、単に印刷と植字業界のダミーテキストです。不明なプリンタフォントが1500年代に使用して以来、業界の標準ダミーテキストを混同基づいてギャラリーを作成するときにLoremイプサムは、単に型標本帳の名前です。",
	"tamamlandi" => "完成した",
	"alisveris_sepeti" => "ショッピングカート",
	"sepetteki_urun" =>"カートに入れる1製品があります。",
	"urun"=>"製品",
	"teslimat"=>"配達",
	"fiyat"=>"価格"
)
?>
